dependencies:
- name: cloudbees-godemo
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.7
- name: cloudbees-springdemo
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: cojan-demo
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: go-webinar
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: mygo-web
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: predemo-go4
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
